name: Docker Image

on: 
  schedule:
   - cron: "*/1 * * * *"

env:
  DOCKER_REGISTRY: dockerhub.io
  DOCKER_USERNAME: nikhilsaxena
  DOCKER_IMAGE: webapp
  DOCKER_IMAGE_TAG: v1 

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      run: echo docker build -t $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_IMAGE_TAG

  docker-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Publish
      run: echo docker push $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_IMAGE_TAG

  docker-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Deploy
      run: echo docker run -it -p 8080:8080 $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_IMAGE_TAG