name: Generate ASCII Artwork

on: push

jobs:
  build_job:
    runs_on: ubuntu-latest
    steps:
    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y

    - name: Execute Cowsay CMD
      run: cowsay -f dragon "Run for cover, I am a DRAGON...." >> dragon.txt

    - name: Upload Artifact(txt file)
      uses: actions/upload-artifact@v3
      with:
        name: dargon-text-file
        path: dragon.txt
  
  test_job:
    needs: build_job
    runs_on: ubuntu-latest
    steps:
    - name: Download Artifact(txt file)
      uses: actions/download-artifact@v3
      with:
        name: dragon-text-file

    - name: Test File Exists
      run: grep -i "dragon" dragon.txt

  deploy_job:
    needs: test_job
    runs_on: ubuntu-latest
    steps:
    - name: Download Artifact(txt file)
      uses: actions/download-artifact@v3
      with:
        name: dragon-text-file

    - name: Read File
      run: cat dragon.txt

    - name: Deploy
      run: echo Deploying...